apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: 654654291247.dkr.ecr.us-east-1.amazonaws.com/pingpong:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pingpong-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: pingpong
