pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = '654654291247'
        AWS_REGION = 'us-east-1'
        ECR_REPO = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/pingpong"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from GitHub...'
                git branch: 'master', url: 'https://github.com/Fox-R-fox/Ponnggame.git'
            }
        }

        stage('Install Maven') {
            steps {
                echo 'Installing Maven...'
                sh '''
                    if ! command -v mvn &> /dev/null; then
                        echo "Maven not found, installing Maven..."
                        wget https://downloads.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
                        tar -xzvf apache-maven-3.8.4-bin.tar.gz
                        mv apache-maven-3.8.4 /opt/maven
                        export PATH=$PATH:/opt/maven/bin
                        echo "Maven installed successfully."
                    else
                        echo "Maven already installed."
                    fi
                '''
            }
        }

        stage('Build') {
            steps {
                echo 'Building the Pong Game...'
                script {
                    // Use Maven command to build the project
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Building Docker Image...'
                sh "docker build -t pingpong:latest ."
            }
        }

        stage('Push to ECR') {
            steps {
                echo 'Pushing Docker Image to AWS ECR...'
                withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
                    sh """
                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}
                    docker tag pingpong:latest ${ECR_REPO}:latest
                    docker push ${ECR_REPO}:latest
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying to Kubernetes...'
                sh "kubectl apply -f kubernetes/deployment.yaml"
            }
        }
    }
}
